const $=(id)=>document.getElementById(id);let last;const bridge=globalThis.pluginGuard;
function markdownText(value){return String(value??'').replace(/[\r\n\t]+/g,' ').replace(/\\/g,'\\\\').replace(/([`*_[\]<>#])/g,'\\$1')}
function markdownCode(value){return '`'+String(value??'').replace(/[\r\n\t]+/g,' ').replace(/`/g,'ˋ')+'`'}
function markdown(report){const rows=['# Plugin Guard report','','Scanned: '+markdownText(report.scannedAt),'Files: '+Number(report.files||0)+'; bytes: '+Number(report.bytes||0),'','## Findings'];for(const x of [...report.issues,...report.risks])rows.push('- '+markdownCode(x.level)+' '+markdownCode(x.code)+(x.file?' — '+markdownCode(x.file):'')+': '+markdownText(x.message));return rows.join('\n')}
async function copy(text,label){try{if(bridge?.copyText)await bridge.copyText(text);else await navigator.clipboard.writeText(text);$('status').textContent=label}catch{$('status').textContent='Copy unavailable'}}
$('choose').addEventListener('click',async()=>{try{if(!bridge)throw new Error('Plugin Guard bridge is unavailable.');await bridge.choosePluginDirectory();$('status').textContent='Directory permission granted; nothing scanned yet.'}catch(e){$('status').textContent=e.message}});
$('scan').addEventListener('click',async()=>{try{if(!bridge)throw new Error('Plugin Guard bridge is unavailable.');$('status').textContent='Scanning read-only…';last=await bridge.scan();$('map').textContent=last.manifest?`${last.manifest.name} · ${last.manifest.features.map(f=>f.code).join(', ')||'no features'}`:'No valid manifest';$('inventory').textContent=`${last.files} files · ${last.bytes.toLocaleString()} bytes`; $('risks').replaceChildren();for(const finding of [...last.issues,...last.risks]){const li=document.createElement('li');li.className=finding.level;li.textContent=`${finding.level.toUpperCase()} ${finding.code}${finding.file?' · '+finding.file:''}: ${finding.message}`;$('risks').append(li)}$('status').textContent='Read-only scan complete'}catch(e){$('status').textContent=e.message}});
$('copyMarkdown').addEventListener('click',()=>last&&copy(markdown(last),'Masked Markdown report copied'));
$('copyJson').addEventListener('click',()=>last&&copy(JSON.stringify(last,null,2),'Masked JSON report copied'));
