const $=(id)=>document.getElementById(id);let plan,zipToken,destinationToken,filesToken;const bridge=globalThis.archiveWorkbench;
function render(next){plan=next;$('tree').replaceChildren();for(const entry of plan.entries){const li=document.createElement('li');li.textContent=`▣ ${entry.name} · ${entry.size.toLocaleString()} B`;$('tree').append(li)}$('summary').textContent=`${plan.entries.length} entries, ${plan.total.toLocaleString()} expanded bytes. Default conflicts: rename. Preview has written nothing.`;}
function requireBridge(){if(!bridge)throw new Error('Archive capability bridge is unavailable in this host.');}
$('chooseZip').addEventListener('click',async()=>{try{requireBridge();zipToken=await bridge.chooseZip();$('status').textContent='ZIP permission granted; preview before extraction.'}catch(e){$('status').textContent=e.message}});
$('inspect').addEventListener('click',async()=>{try{requireBridge();if(!zipToken)throw new Error('Choose a ZIP first.');render(await bridge.preview(zipToken));$('status').textContent='All entries passed preflight'}catch(e){$('status').textContent=e.message;$('summary').textContent='Archive blocked before any write.'}});
$('chooseDestination').addEventListener('click',async()=>{try{requireBridge();destinationToken=await bridge.chooseDestination();$('status').textContent='Destination permission granted; no files written.'}catch(e){$('status').textContent=e.message}});
$('extract').addEventListener('click',async()=>{try{requireBridge();if(!zipToken||!destinationToken)throw new Error('Choose both a ZIP and destination first.');if(!confirm('Extract this preflighted ZIP with rename-on-collision? Existing files will not be overwritten.'))return;render(await bridge.extract(zipToken,destinationToken));$('status').textContent='Extraction completed with rename-on-collision'}catch(e){$('status').textContent=e.message}});
$('chooseFiles').addEventListener('click',async()=>{try{requireBridge();filesToken=await bridge.chooseFiles();$('status').textContent='Source files granted; create writes only after a save dialog.'}catch(e){$('status').textContent=e.message}});
$('create').addEventListener('click',async()=>{try{requireBridge();if(!filesToken)throw new Error('Choose files first.');if(!confirm('Create a stored ZIP from the selected files?'))return;const result=await bridge.create(filesToken);$('status').textContent=`Created ${result.entries} entries safely.`}catch(e){$('status').textContent=e.message}});
$('copy').addEventListener('click',async()=>{if(!plan)return;const text=JSON.stringify(plan,null,2);try{if(bridge?.copyText)await bridge.copyText(text);else await navigator.clipboard.writeText(text);$('status').textContent='Plan copied'}catch{$('status').textContent='Copy unavailable'}});
