import { detectSensitive, imageExportDecision, redactText } from '../core/sanitize.mjs';
const $ = (id) => document.getElementById(id);
const input = $('input'), status = $('status'), findings = $('findings');
let masks = [], image = null, dragging = null;
const allowed = () => $('whitelist').value.split('\n').map((v) => v.trim()).filter(Boolean);
function scan() { const result = detectSensitive(input.value, { whitelist: allowed() }); findings.replaceChildren(); for (const item of result) { const li = document.createElement('li'); li.textContent = `${item.type} · ${item.value}`; findings.append(li); } $('summary').textContent = `${result.length} item(s) need review.`; status.textContent = result.length ? 'Review required' : 'No matched sensitive data'; return result; }
$('scan').addEventListener('click',()=>{try{scan()}catch(error){status.textContent=error.message}});
$('redact').addEventListener('click', () => { try { const result = redactText(input.value, { whitelist: allowed() }); input.value = result.text; scan(); status.textContent = `Redacted ${result.findings.length} item(s)`; } catch (error) { status.textContent = error.message; } });
$('copy').addEventListener('click', async () => { try { const current=detectSensitive(input.value,{whitelist:allowed()}); if(current.length){scan();status.textContent='Sensitive matches remain. Apply redaction before copying.';return} if (globalThis.shareSanitizer?.copyText) await globalThis.shareSanitizer.copyText(input.value); else await navigator.clipboard.writeText(input.value); status.textContent = 'Safe text copied'; } catch (error) { status.textContent = error.message || 'Copy unavailable in this host'; } });
const canvas = $('canvas'), ctx = canvas.getContext('2d');
function draw() { if (!image) return; canvas.width = image.naturalWidth; canvas.height = image.naturalHeight; ctx.drawImage(image, 0, 0); ctx.fillStyle = '#ef5c5c'; for (const m of masks) ctx.fillRect(m.x,m.y,m.w,m.h); }
function loadImage(file){if(!file||!/^image\/(?:png|jpeg|webp)$/i.test(file.type)||file.size>20*1024*1024){status.textContent='Only PNG/JPEG/WebP images up to 20 MiB are accepted.';return}const url=URL.createObjectURL(file);image=new Image();image.onload=()=>{if(image.naturalWidth*image.naturalHeight>40_000_000){status.textContent='Image exceeds the 40 megapixel safety limit.';image=null;URL.revokeObjectURL(url);return}masks=[];$('imageDesk').hidden=false;draw();URL.revokeObjectURL(url)};image.onerror=()=>{image=null;URL.revokeObjectURL(url);status.textContent='Image decoding failed; nothing was changed.'};image.src=url;$('ocr').textContent='TextDetector'in globalThis?'Browser text detection is available, but is not run automatically.':'OCR is unavailable in this host; use manual masks.';}
$('image').addEventListener('change', (event) => loadImage(event.target.files?.[0]));
function pos(event){const r=canvas.getBoundingClientRect(),sx=canvas.width/r.width,sy=canvas.height/r.height;return{x:(event.clientX-r.left)*sx,y:(event.clientY-r.top)*sy};}
canvas.addEventListener('pointerdown',(e)=>{dragging=pos(e);canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointerup',(e)=>{if(!dragging)return;const end=pos(e);masks.push({x:Math.min(dragging.x,end.x),y:Math.min(dragging.y,end.y),w:Math.abs(end.x-dragging.x),h:Math.abs(end.y-dragging.y)});dragging=null;draw()});canvas.addEventListener('pointercancel',()=>{dragging=null});
$('clearMasks').addEventListener('click',()=>{masks=[];draw()});$('exportImage').addEventListener('click',async()=>{try{let decision=imageExportDecision(masks.length);if(!decision.ok){if(!confirm('No manual masks were added. Export only to strip metadata, without claiming visual redaction?')){status.textContent='Image export cancelled; add masks for a visually redacted image.';return}decision=imageExportDecision(masks.length,true)}const data=canvas.toDataURL('image/png');if(globalThis.shareSanitizer?.copyImage)await globalThis.shareSanitizer.copyImage(data);else{const a=document.createElement('a');a.href=data;a.download='sanitized.png';a.click()}status.textContent=decision.mode==='metadata-only'?'Metadata-only image export completed; no visual redaction was applied.':'Redacted image exported'}catch{status.textContent='Image export unavailable'}});
async function consumeEntry(action){const payload=action?.payload;const type=action?.type;if(type==='over'||typeof payload==='string'){input.value=String(payload||'').slice(0,1024*1024);scan();return}const file=Array.isArray(payload)?payload[0]:payload;if(!file)return;if(type==='img'||/^image\//i.test(file.type||'')){loadImage(file);return}if((file.size||0)>1024*1024||!/(?:\.txt|\.md|\.json|\.log)$/i.test(file.name||'')){status.textContent='Only selected text files up to 1 MiB are accepted.';return}if(typeof file.text!=='function'){status.textContent='Selected text is unavailable in this host.';return}input.value=await file.text();scan();}
globalThis.ztools?.onPluginEnter?.((action)=>{consumeEntry(action).catch(()=>{status.textContent='Could not load plugin entry data safely.'})});
