'use strict';
const fs = require('node:fs/promises');
const path = require('node:path');
const { randomBytes } = require('node:crypto');
const api = globalThis.ztools || {};
const selected = new Map();
const GRANT_TTL_MS = 5 * 60 * 1000, ZIP_SOURCE_MAX = 256 * 1024 * 1024, CREATE_FILE_MAX = 64 * 1024 * 1024, CREATE_TOTAL_MAX = 256 * 1024 * 1024, CREATE_COUNT_MAX = 100, MAX_GRANTS = 32;
function clearExpired(){for(const [id,item] of selected)if(item.expires<Date.now())selected.delete(id)}
function token(kind,value) { clearExpired(); if(selected.size>=MAX_GRANTS) throw new Error('Too many active file grants; leave and re-open the plugin.'); const id=randomBytes(24).toString('base64url'); selected.set(id, { kind, value, expires: Date.now() + GRANT_TTL_MS }); return id; }
function grant(id,kind) { clearExpired(); const item = selected.get(String(id)); if (!item || item.kind!==kind) throw new Error('The selected path grant is invalid or expired; choose it again.'); return item.value; }
function pathsFrom(result) { if (typeof result === 'string') return [result]; if (Array.isArray(result)) return result; return Array.isArray(result && result.filePaths) ? result.filePaths : []; }
async function choose(options) { if (typeof api.showOpenDialog !== 'function') throw new Error('This ZTools host does not provide a file dialog.'); const values = pathsFrom(await api.showOpenDialog(options)); if (!values.length) throw new Error('Selection cancelled.'); return values; }
async function save(options) { if (typeof api.showSaveDialog !== 'function') throw new Error('This ZTools host does not provide a save dialog.'); const result = await api.showSaveDialog(options); const value = typeof result === 'string' ? result : result && (result.filePath || result.path); if (!value) throw new Error('Save cancelled.'); return value; }
async function core() { return import('../core/archive.mjs'); }
function summary(plan) { return { format: plan.format, entries: plan.entries.map((entry) => ({ name: entry.name, size: entry.size, compressed: entry.compressed })), total: plan.total, conflict: plan.conflict }; }
async function safeFile(input, maxSize, extension) { const initial = await fs.lstat(input); if (initial.isSymbolicLink() || !initial.isFile()) throw new Error('Only a directly selected regular file is allowed.'); const resolved = await fs.realpath(input); const final = await fs.lstat(resolved); if (final.isSymbolicLink() || !final.isFile() || final.size > maxSize) throw new Error('Selected file is unsafe or exceeds the size limit.'); if (extension && path.extname(resolved).toLowerCase() !== extension) throw new Error(`Expected a ${extension} file.`); return { path: resolved, size: final.size }; }
async function safeDirectory(input) { const selectedPath = path.resolve(input); let current = path.parse(selectedPath).root; for (const part of path.relative(current, selectedPath).split(path.sep).filter(Boolean)) { current = path.join(current, part); const info = await fs.lstat(current); if (info.isSymbolicLink()) throw new Error('Extraction destination contains a symbolic-link ancestor.'); } const initial = await fs.lstat(selectedPath); if (initial.isSymbolicLink() || !initial.isDirectory()) throw new Error('Extraction destination must be a real directory.'); const resolved = await fs.realpath(selectedPath); const final = await fs.lstat(resolved); if (final.isSymbolicLink() || !final.isDirectory()) throw new Error('Extraction destination changed after selection.'); current = path.parse(resolved).root; for (const part of path.relative(current, resolved).split(path.sep).filter(Boolean)) { current = path.join(current, part); const info = await fs.lstat(current); if (info.isSymbolicLink()) throw new Error('Extraction destination contains a symbolic-link ancestor.'); } return resolved; }
const bridge = {
  chooseZip: async () => token('zip',await safeFile((await choose({ title: 'Choose ZIP archive', properties: ['openFile'], filters: [{ name: 'ZIP archive', extensions: ['zip'] }] }))[0], ZIP_SOURCE_MAX, '.zip')),
  chooseDestination: async () => token('destination',await safeDirectory((await choose({ title: 'Choose extraction destination', properties: ['openDirectory', 'createDirectory'] }))[0])),
  chooseFiles: async () => { const inputs = await choose({ title: 'Choose files to archive', properties: ['openFile', 'multiSelections'] }); if (inputs.length > CREATE_COUNT_MAX) throw new Error('Choose at most 100 files.'); let total = 0; const safe = []; for (const input of inputs) { const item = await safeFile(input, CREATE_FILE_MAX); total += item.size; if (total > CREATE_TOTAL_MAX) throw new Error('Selected files exceed the 256 MiB total limit.'); safe.push(item); } return token('files',safe); },
  preview: async (zipToken) => { const zip = grant(zipToken,'zip'); const current = await safeFile(zip.path, ZIP_SOURCE_MAX, '.zip'); return summary((await core()).planExtraction(await fs.readFile(current.path), { conflict: 'rename' })); },
  extract: async (zipToken, destinationToken) => { const zip = grant(zipToken,'zip'), destination = grant(destinationToken,'destination'); const current = await safeFile(zip.path, ZIP_SOURCE_MAX, '.zip'); const destinationPath = await safeDirectory(destination); const mod = await core(); return summary(await mod.extractZipSafely(await fs.readFile(current.path), destinationPath, { conflict: 'rename' })); },
  create: async (filesToken) => { const inputs = grant(filesToken,'files'); if (!Array.isArray(inputs) || !inputs.length || inputs.length > CREATE_COUNT_MAX) throw new Error('File selection permission is no longer valid.'); const mod = await core(); let total = 0; const entries = []; for (const input of inputs) { const current = await safeFile(input.path, CREATE_FILE_MAX); total += current.size; if (total > CREATE_TOTAL_MAX) throw new Error('Selected files exceed the 256 MiB total limit.'); entries.push({ name: path.basename(current.path), data: await fs.readFile(current.path) }); } const bytes = mod.createStoredZip(entries); const target = await save({ title: 'Save ZIP archive', defaultPath: 'archive-workbench.zip', filters: [{ name: 'ZIP archive', extensions: ['zip'] }] }); try { await fs.lstat(target); throw new Error('Refusing to overwrite an existing file. Choose a new name.'); } catch (error) { if (error && error.code !== 'ENOENT') throw error; } await fs.writeFile(target, bytes, { mode: 0o600, flag: 'wx' }); return { path: target, entries: entries.length }; },
  copyText: typeof api.copyText === 'function' ? (text) => api.copyText(String(text)) : undefined
};
globalThis.archiveWorkbench = Object.freeze(bridge);
if (typeof api.onPluginOut === 'function') api.onPluginOut(() => selected.clear());
