import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,writeFile,symlink,mkdir}from 'node:fs/promises';import {tmpdir}from 'node:os';import path from 'node:path';import {scanPlugin,safeRelative,maskSecrets,toMarkdown}from '../src/core/guard.mjs';
async function fixture(files={}){const root=await mkdtemp(path.join(tmpdir(),'guard-'));for(const [name,value] of Object.entries(files)){const p=path.join(root,name);await mkdir(path.dirname(p),{recursive:true});await writeFile(p,value)}return root}
test('rejects unsafe entrypoint paths and secret exposure',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'../oops',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],features:[{code:'bad',cmds:['files']}]}),'logo.svg':'x','preload.cjs':"const key='sk-abcdefghijklmnopqrstuvwxyz'"});const r=await scanPlugin(root);assert.ok(r.issues.some(x=>x.code==='entrypoint'));assert.ok(r.risks.some(x=>x.code==='secret'));assert.ok(!JSON.stringify(r).includes('abcdefghijklmnopqrstuvwxyz'));});
test('does not follow symlinks',async()=>{const root=await fixture({'plugin.json':'{}'});await symlink('/tmp',path.join(root,'out'));const r=await scanPlugin(root);assert.ok(r.issues.some(x=>x.code==='symlink'));});
test('path policy is platform-independent',()=>{assert.equal(safeRelative('../x'),false);assert.equal(safeRelative('C:\\x'),false);assert.equal(safeRelative('src/main.js'),true);assert.match(maskSecrets('token=abcdefghijklmnop'),/masked/);});
test('fails closed for unknown preload bridge fields',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',platform:['darwin','win32','linux'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'bridge.readEverything = () => 1'});const r=await scanPlugin(root);assert.ok(r.risks.some(x=>x.code==='unknown-bridge'));});
test('only returns masked report fields and follows Node relative-require candidates',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'token=abcdefghijklmnop',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',categories:['other'],features:[{code:'safe'}]}), 'index.html':'ok','logo.svg':'x','preload.cjs':"require('./helper')",'helper.js':'module.exports=1','token=abcdefghijklmnop.js':'x'});const r=await scanPlugin(root);assert.ok(!JSON.stringify(r).includes('abcdefghijklmnop'));assert.equal(r.risks.some(x=>x.code==='missing-relative-require'),false);});
test('scans full audited text beyond the former snippet boundary',async()=>{const root=await fixture({'plugin.json':JSON.stringify({name:'x',version:'1',author:'a',main:'index.html',logo:'logo.svg',preload:'preload.cjs',categories:['other'],features:[]}), 'index.html':'ok','logo.svg':'x','preload.cjs':'x'.repeat(100000)+'\neval(1)'});const r=await scanPlugin(root);assert.ok(r.risks.some(x=>x.code==='eval'));});
test('markdown report escapes untrusted file names and finding text',()=>{const value=toMarkdown({scannedAt:'now',files:1,bytes:1,issues:[{level:'high',code:'x`\n## forged',file:'bad`\n- injected.md',message:'line\n# fake'}],risks:[]});assert.ok(!value.includes('\n## forged'));assert.ok(!value.includes('\n- injected.md'));assert.ok(!value.includes('\n# fake'));});
