import { parseHar, analyze, redact, diffReports, toMarkdown } from '../core/analyze.js';
const $=s=>document.querySelector(s),out=$('#summary'),waterfall=$('#waterfall');let reports=[];
function el(tag,text,className){const x=document.createElement(tag);if(text!==undefined)x.textContent=String(text);if(className)x.className=className;return x;}
function render(){const report=reports[0];out.replaceChildren();waterfall.replaceChildren();if(!report)return;for(const [k,v]of [['entries',report.entries],['time',`${report.totalMs}ms`],['errors',report.errors.length],['transfer',`${report.transferredBytes}B`]]){const card=el('article','', 'card');card.append(el('small',k),el('strong',v));out.append(card);}if(reports[1])out.append(el('article',`environment delta: ${JSON.stringify(diffReports(report,reports[1]))}`,'card'));const slow=report.slow.slice(0,16),longest=Math.max(1,...slow.map(item=>item.duration));if(!slow.length)waterfall.append(el('div','No requests over 1 second.','bar'));for(const item of slow){const row=el('div','', 'bar'),bar=el('i','');bar.style.setProperty('--fraction',String(Math.max(.02,item.duration/longest)));row.append(el('code',`${item.status} ${item.method}`),bar,el('span',`${Math.round(item.duration)}ms`),el('span',item.url));waterfall.append(row);}}
function setReports(texts){reports=texts.map(t=>analyze(parseHar(t)));render();}
$('#run').addEventListener('click',()=>{try{setReports([$('#input').value]);}catch(e){out.replaceChildren(el('p',e.message));waterfall.replaceChildren();}});
$('#choose').addEventListener('click',async()=>{try{await window.harDoctor?.choose?.();const files=window.harDoctor?.readGranted?.();if(!files)throw Error('ZTools bridge unavailable');setReports(files);}catch(e){out.replaceChildren(el('p',e.message));}});
$('#copy-md').addEventListener('click',()=>{if(reports[0])window.harDoctor?.copyText?.(toMarkdown(reports[0],reports[1]&&diffReports(reports[0],reports[1])));});
$('#copy-json').addEventListener('click',()=>{if(reports[0])window.harDoctor?.copyText?.(JSON.stringify(redact(reports),null,2));});
