import { inflateRawSync } from 'node:zlib';
import { randomBytes } from 'node:crypto';
import { link, lstat, mkdir, realpath, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
const LIMITS = Object.freeze({ entries: 1200, single: 64 * 1024 * 1024, total: 256 * 1024 * 1024, ratio: 120, depth: 20, name: 240 });
const textDecoder = new TextDecoder('utf-8', { fatal: true });
function fail(message) { throw new Error(message); }
function u16(v, at) { if(at+2>v.byteLength) fail('Truncated ZIP record.'); return v.getUint16(at,true); }
function u32(v, at) { if(at+4>v.byteLength) fail('Truncated ZIP record.'); return v.getUint32(at,true); }
function reservedWindows(segment) { return /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i.test(segment) || /[. ]$/.test(segment); }
export function normalizeEntryName(name) {
  if(typeof name!=='string'||!name||name.includes('\0')||new TextEncoder().encode(name).byteLength>LIMITS.name) fail('Invalid entry name.');
  if(name.includes('\\')||/^\//.test(name)||/^(?:[A-Za-z]:|\\\\)/.test(name)) fail(`Unsafe archive path: ${name}`);
  const directory=name.endsWith('/'), raw=directory?name.slice(0,-1):name; const parts=raw.normalize('NFC').split('/'); if(parts.some((x)=>!x||x==='.'||x==='..'||reservedWindows(x))) fail(`Unsafe archive path: ${name}`); if(parts.length>LIMITS.depth) fail('Archive path exceeds depth limit.'); return parts.join('/')+(directory?'/':'');
}
export function collisionKey(name) { return normalizeEntryName(name).replace(/\/$/,'').normalize('NFC').toLocaleLowerCase('en-US'); }
function findEocd(bytes) { const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength); for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p-=1) if(u32(view,p)===0x06054b50) return p; fail('ZIP end record not found.'); }
function decode(bytes) { try{return textDecoder.decode(bytes)}catch{fail('ZIP filename is not valid UTF-8.')} }
export function inspectZip(input, options={}) {
  const bytes=input instanceof Uint8Array?input:new Uint8Array(input); const limits={...LIMITS,...(options.limits||{})}; const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength); const eocd=findEocd(bytes); const disk=u16(view,eocd+4),cdDisk=u16(view,eocd+6),entriesDisk=u16(view,eocd+8),entriesCount=u16(view,eocd+10),cdSize=u32(view,eocd+12),cdOffset=u32(view,eocd+16),comment=u16(view,eocd+20); if(disk||cdDisk||entriesDisk!==entriesCount||entriesCount===0xffff||cdSize===0xffffffff||cdOffset===0xffffffff||eocd+22+comment!==bytes.length) fail('Multi-disk, ZIP64, or malformed ZIP end record is rejected.'); if(entriesCount>limits.entries||cdOffset+cdSize>eocd) fail('ZIP central directory exceeds safety limits.');
  let at=cdOffset,total=0;const entries=[],seen=new Set(); for(let i=0;i<entriesCount;i+=1){if(at+46>cdOffset+cdSize||u32(view,at)!==0x02014b50)fail('Invalid ZIP central directory entry.');const flags=u16(view,at+8),method=u16(view,at+10),crc=u32(view,at+16),compressed=u32(view,at+20),size=u32(view,at+24),nameLength=u16(view,at+28),extra=u16(view,at+30),entryComment=u16(view,at+32),attrs=u32(view,at+38),offset=u32(view,at+42),end=at+46+nameLength+extra+entryComment;if(end>cdOffset+cdSize||compressed===0xffffffff||size===0xffffffff||offset===0xffffffff)fail('ZIP64 or malformed central entry is rejected.');if(flags&1||flags&8)fail('Encrypted or data-descriptor ZIP entries are rejected.');if(![0,8].includes(method))fail('Unsupported ZIP compression method.');if((method===0&&size>0&&compressed===0)||size>limits.single||(compressed&&size/compressed>limits.ratio))fail('ZIP entry exceeds expansion safety limits.');const name=normalizeEntryName(decode(bytes.subarray(at+46,at+46+nameLength)));const key=collisionKey(name);if(seen.has(key))fail(`Case or Unicode collision: ${name}`);seen.add(key);const mode=attrs>>>16,type=mode&0o170000,directory=name.endsWith('/');if(type&&type!==0o100000&&type!==0o40000)fail(`Unsafe special archive entry: ${name}`);if((type===0o40000&&!directory)||(directory&&(size!==0||compressed!==0||method!==0)))fail(`Unsafe directory entry: ${name}`);total+=size;if(total>limits.total)fail('ZIP total expansion exceeds safety limits.');entries.push({name,key,flags,method,crc,compressed,size,offset,attrs,directory,centralOffset:cdOffset});at=end;}if(at!==cdOffset+cdSize)fail('ZIP central directory size does not match entries.');for(const entry of entries)validateLocalRecord(bytes,entry,cdOffset);
  return {format:'zip',entries,total,limits};
}
function validateLocalRecord(bytes, entry, centralOffset) { const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),at=entry.offset;if(at>=centralOffset||u32(view,at)!==0x04034b50)fail(`Missing local header for ${entry.name}.`);const flags=u16(view,at+6),method=u16(view,at+8),crc=u32(view,at+14),compressed=u32(view,at+18),size=u32(view,at+22),nameLength=u16(view,at+26),extra=u16(view,at+28),start=at+30+nameLength+extra,end=start+entry.compressed;if(flags!==entry.flags||method!==entry.method||crc!==entry.crc||compressed!==entry.compressed||size!==entry.size||start>centralOffset||end>centralOffset)fail(`Local header mismatch for ${entry.name}.`);const localName=normalizeEntryName(decode(bytes.subarray(at+30,at+30+nameLength)));if(localName!==entry.name)fail(`Local filename mismatch for ${entry.name}.`);return { start, end }; }
function localData(bytes, entry) { const {start,end}=validateLocalRecord(bytes,entry,entry.centralOffset);const raw=bytes.subarray(start,end);const value=entry.method===0?raw:inflateRawSync(raw,{maxOutputLength:entry.size+1});if(value.length!==entry.size||crc32(value)!==entry.crc)fail(`ZIP checksum mismatch for ${entry.name}.`);return value; }
export function planExtraction(input, options={}) { const archive=inspectZip(input,options);const policy=options.conflict||'rename';if(!['rename','skip','error'].includes(policy))fail('Unknown conflict policy.');return {...archive,conflict:policy,writeOrder:archive.entries.map((e)=>({from:e.name,to:e.name,action:policy==='rename'?'rename-on-conflict':'write-or-'+policy}))}; }
async function ensureSafeParents(root, target) { const rel=path.relative(root,target);if(!rel||rel.startsWith('..')||path.isAbsolute(rel))fail('Output escaped destination.');let current=root;for(const part of rel.split(path.sep).slice(0,-1)){current=path.join(current,part);try{const s=await lstat(current);if(s.isSymbolicLink()||!s.isDirectory())fail('Unsafe output ancestor.')}catch(e){if(e.code!=='ENOENT')throw e;await mkdir(current,{recursive:false,mode:0o700});}} }
async function assertNoSymlinkAncestors(input) { const full=path.resolve(input), root=path.parse(full).root; let current=root; for(const part of path.relative(root,full).split(path.sep).filter(Boolean)){current=path.join(current,part);const info=await lstat(current);if(info.isSymbolicLink())fail('Unsafe extraction destination root.');} }
export async function extractZipSafely(input,destination,options={}) { const bytes=input instanceof Uint8Array?input:new Uint8Array(input);const plan=planExtraction(bytes,options);const selected=path.resolve(destination),selectedInfo=await lstat(selected);if(selectedInfo.isSymbolicLink()||!selectedInfo.isDirectory())fail('Unsafe extraction destination root.');const root=await realpath(selected);await assertNoSymlinkAncestors(root);const rootInfo=await lstat(root);if(rootInfo.isSymbolicLink()||!rootInfo.isDirectory())fail('Unsafe extraction destination root.');for(const entry of plan.entries){await assertNoSymlinkAncestors(root);const parts=entry.name.split('/').filter(Boolean),target=path.resolve(root,...parts);await ensureSafeParents(root,target);if(entry.directory){try{const info=await lstat(target);if(info.isSymbolicLink()||!info.isDirectory())fail(`Unsafe directory collision: ${entry.name}`)}catch(error){if(error.code==='ENOENT')await mkdir(target,{mode:0o700});else throw error}continue}let final=target;try{await lstat(final);if(plan.conflict==='skip')continue;if(plan.conflict==='error')fail(`Destination collision: ${entry.name}`);let n=1;while(true){const candidate=`${target} (${n})`;try{await lstat(candidate);n+=1}catch(e){if(e.code==='ENOENT'){final=candidate;break;}throw e}}}catch(e){if(e.code!=='ENOENT')throw e}const temp=`${final}.archive-workbench-${randomBytes(12).toString('hex')}`;try{await assertNoSymlinkAncestors(root);await ensureSafeParents(root,final);await writeFile(temp,localData(bytes,entry),{mode:0o600,flag:'wx'});await assertNoSymlinkAncestors(root);await ensureSafeParents(root,final);await link(temp,final);await rm(temp,{force:true});await assertNoSymlinkAncestors(root)}catch(e){await rm(temp,{force:true}).catch(()=>{});throw e}}return plan; }
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i+=1)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function put16(a,n){a.push(n&255,(n>>>8)&255)}function put32(a,n){a.push(n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255)}
export function createStoredZip(entries) { if(!Array.isArray(entries)||entries.length>LIMITS.entries||entries.length>0xffff)fail('Too many ZIP entries.');const parts=[],central=[];let offset=0,total=0;const seen=new Set();for(const item of entries){const name=normalizeEntryName(item.name),key=collisionKey(name);if(name.endsWith('/')||seen.has(key))fail(`Case, Unicode, or directory collision: ${name}`);seen.add(key);const data=item.data instanceof Uint8Array?item.data:new TextEncoder().encode(String(item.data??''));if(data.length>LIMITS.single||data.length>0xffffffff||(total+=data.length)>LIMITS.total)fail('Entry exceeds size limit.');const nb=new TextEncoder().encode(name),crc=crc32(data),local=[];put32(local,0x04034b50);put16(local,20);put16(local,0x800);put16(local,0);put16(local,0);put16(local,0);put32(local,crc);put32(local,data.length);put32(local,data.length);put16(local,nb.length);put16(local,0);const header=Uint8Array.from(local);parts.push(header,nb,data);const c=[];put32(c,0x02014b50);put16(c,20);put16(c,20);put16(c,0x800);put16(c,0);put16(c,0);put16(c,0);put32(c,crc);put32(c,data.length);put32(c,data.length);put16(c,nb.length);put16(c,0);put16(c,0);put16(c,0);put16(c,0);put32(c,0);put32(c,offset);central.push(Uint8Array.from(c),nb);offset+=header.length+nb.length+data.length;if(offset>0xffffffff)fail('ZIP64 output is not supported.');}const cdOffset=offset,cdSize=central.reduce((n,x)=>n+x.length,0);if(cdSize>0xffffffff||cdOffset+cdSize>0xffffffff)fail('ZIP64 output is not supported.');const end=[];put32(end,0x06054b50);put16(end,0);put16(end,0);put16(end,entries.length);put16(end,entries.length);put32(end,cdSize);put32(end,cdOffset);put16(end,0);const all=[...parts,...central,Uint8Array.from(end)];const size=all.reduce((n,item)=>n+item.length,0);if(size>LIMITS.total+LIMITS.entries*512)fail('ZIP output exceeds safety limit.');const out=new Uint8Array(size);let at=0;for(const item of all){out.set(item,at);at+=item.length}return out;}
export { LIMITS };
